// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlFQRkYRTaspbRDW4F2u8Qzqw9haJnvJc',
    appId: '1:499980746604:web:707d179726c197460afd49',
    messagingSenderId: '499980746604',
    projectId: 'flipflow-app',
    authDomain: 'flipflow-app.firebaseapp.com',
    storageBucket: 'flipflow-app.appspot.com',
    measurementId: 'G-YM9TJCQJGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeb45TswO01IkFIQVzwhaEPFgx5r1IJiY',
    appId: '1:499980746604:android:cc3b0f9d47d323f20afd49',
    messagingSenderId: '499980746604',
    projectId: 'flipflow-app',
    storageBucket: 'flipflow-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABQqsQLStuyiy6poec8ba9WAYMt0iP0c4',
    appId: '1:499980746604:ios:b8bad455baa811690afd49',
    messagingSenderId: '499980746604',
    projectId: 'flipflow-app',
    storageBucket: 'flipflow-app.appspot.com',
    iosBundleId: 'com.example.flipflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABQqsQLStuyiy6poec8ba9WAYMt0iP0c4',
    appId: '1:499980746604:ios:b8bad455baa811690afd49',
    messagingSenderId: '499980746604',
    projectId: 'flipflow-app',
    storageBucket: 'flipflow-app.appspot.com',
    iosBundleId: 'com.example.flipflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlFQRkYRTaspbRDW4F2u8Qzqw9haJnvJc',
    appId: '1:499980746604:web:de999fff14ba25660afd49',
    messagingSenderId: '499980746604',
    projectId: 'flipflow-app',
    authDomain: 'flipflow-app.firebaseapp.com',
    storageBucket: 'flipflow-app.appspot.com',
    measurementId: 'G-TSQQZYSDK7',
  );

}